baseURL = "https://www.exploringdata.org/"
languageCode = "en-us"
title = "Exploring Data"
theme = "minimal"
rssLimit = 6  # Maximum number of items in the RSS feed.
disqusShortname = "https-www-exploringdata-org" # delete this to disable disqus comments

googleAnalytics = "UA-134222974-1"


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"] 

[params]
    author = "Jason Dexter"
    description = "A Blog on Wrangling and Exploring Data using the `R` programming language"
    githubUsername = "#"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    code_copy_button = true # Turn on/off the code-copy-button for code-fields
    #relatedPosts = false  # Add a related content section to all single posts page
    
    # Add custom css
    #customCSS = ["css/extra.css"]
    

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

#[[menu.main]]
 #   url = "/project/"
  #  name = "Projects"
   # weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


#[[menu.icon]]
 #   url = "mailto:dextersanalytics@gmail.com"
 #   name = "envelope-o"
 #   weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/jdex/"
    name = "linkedin"
    weight = 2

[[menu.icon]]
    url = "https://github.com/dexters-analytics"
    name = "github"
    weight = 3